main(_) :-
    use_foreign_library(sdl),
    sdl_init([video]),
    sdl_create_window("SDL Test", 640, 480, [], Window),
    write("Window: "), write(Window), nl,
    sdl_create_renderer(Window, [software], Renderer),
    write("Renderer: "), write(Renderer), nl,
    sdl_render_color(Renderer, X),
    write("Color: "), write(X), nl,
    write("Red"), nl,
    sdl_render_color(Renderer, rgba(255, 0, 0, 255)),
    sdl_render_clear(Renderer),
    sdl_render_present(Renderer),
    sleep(1),
    write("Green"), nl,
    sdl_render_color(Renderer, rgba(0, 255, 0, 255)),
    sdl_render_clear(Renderer),
    sdl_render_present(Renderer),
    sleep(1),
    write("Blue"), nl,
    sdl_render_color(Renderer, rgba(0, 0, 255, 255)),
    sdl_render_clear(Renderer),
    sdl_render_present(Renderer),
    sleep(1),
    sdl_destroy_renderer(Renderer),
    sdl_destroy_window(Window),
    sdl_terminate.
